### ISSUE TITLE
[Carousel] - Issue with Single Featured Collection

### ISSUE THREAD

**Issue by bensuwun** [DLSU-CSSWENG-Team-2/cmweb-frontend#12]
Data for carousel is mapped properly, but if there's **only one featured collection** the swipe feature breaks.

See transition images below:

**On page load**
![image](https://user-images.githubusercontent.com/59037332/128178567-5a5e4e6e-533b-4da5-a18b-c02c2c973b14.png)

**Swipe to next featured collection** (*supposedly none as there's only one*)
![image](https://user-images.githubusercontent.com/59037332/128178968-169e960d-d5d6-42bd-8420-05e405095045.png)

**Comment by zobhhz** [comment]
To add to this, swiping left to go back to the featured collection also doesn't work however, you can still go back using the tab below.
