### ISSUE TITLE
[Footer] - Links to all socials are missing

### ISSUE THREAD

**Issue by zobhhz** [DLSU-CSSWENG-Team-2/cmweb-frontend#17]
**Summary:**
The social media links found on the footer do not work when clicked. This issue is present when the website is being viewed both in desktops and mobile devices.

**Steps to Reproduce:**
- Scroll down to the bottom of any page to access the footer.
- Click on any socials icon.

**Expected Result:**
It will redirect to the brand's page on that social media platform.

**Actual Result:**
Stays on the website and does not redirect to the social media platform.

<hr>

### More Info:
**Source URL:** https://celestemanila.netlify.app/

**Comment by zobhhz** [comment]
This issue is also present in the desktop version of the website.

**Comment by makorino** [comment]
Hello. I have already fixed the issue. Check the latest merge in production. Thanks!
