### ISSUE TITLE
[Cart] - sizes are not included in cart

### ISSUE THREAD

**Issue by zobhhz** [DLSU-CSSWENG-Team-2/cmweb-frontend#60]
**Summary:**
When adding a product to the cart, the sizes are not included in the edit cart page. Adding the same product but with different sizes is stored as 1 item in the cart rather than 2 separate items.

**Steps to Reproduce:**
- select a product from the `shop` page that has more than 1 size
- add the product to the cart
- add the product again but with a different size
- check the cart

**Expected Result:**
The are 2 separate entries of the same product with their respective sizes, quantities, and subtotal amounts. 

**Actual Result:**
Adding the same product to cart but with different sizes are counted as 1 product in the cart.

<hr>

### More Info:
**Source URL:** https://celestemanila.netlify.app/shop || https://celestemanila.netlify.app/cart

**Screenshots:**
Adding Sofia in Amber (Small):
![image](https://user-images.githubusercontent.com/60706360/131678227-c1bff6dc-e06d-46cb-9d2d-e9d0d34b78e6.png)

Adding Sofia in Amber(Medium):
![image](https://user-images.githubusercontent.com/60706360/131678368-0251bcc3-129a-4293-b319-fc97e4146065.png)

Cart Page:
![image](https://user-images.githubusercontent.com/60706360/131678490-dd6e446b-fc24-4811-9264-0c6c4040f6f4.png)

**Comment by zobhhz** [comment]
Oops sizes are still not included in the cart, perhaps a frontend related issue 🤔

**Comment by AdrielAmoguis** [comment]
Yup, sizes are fully implemented now in the back-end.

**Comment by zobhhz** [comment]
Issue Resolved 🥳
